# ------ root_path/dataset_name ------
root_path: 'data'


# ------ Load Cache and Features ------
load_cache: True
load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True

search_scale: [50, 50]
search_step: [200, 20]

init_beta: 1
init_alpha: 10


# ------ Basic Config ------
dataset: 'oxford_flowers'
shots: 16
backbone: 'ViT-B-32.pt'

lr: 0.001
augment_epoch: 10
train_epoch: 200